name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: sofle-${{ needs.prepare.outputs.short_sha }}